runtime: java17
instance_class: F2

env_variables:
  BUCKET_NAME: "noenavintagedk.appspot.com"

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

entrypoint: "java -cp target/NoenaVintageApp.jar"
health_check:
  enable_health_check: True
